services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    image: isarath4/finance-pulse-backend:latest   # ← prebuilt image
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    environment:
      MONGODB_URI: mongodb://mongo:27017/business_management_system
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    image: isarath4/finance-pulse-frontend:latest  # ← prebuilt image
    restart: unless-stopped
    ports:
      - "8080:80"

  proxy:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/finance-pulse.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo_data:
