version: '3.8'
services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: yourdockerhub/finance-pulse-backend:latest
    restart: unless-stopped
    env_file: 
      - ./backend/.env.production   # create this with your production vars
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourdockerhub/finance-pulse-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"

  proxy:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/finance-pulse.conf:/etc/nginx/conf.d/default.conf:ro
