# Remove the top “version:” line if present.

services:

  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: yourdockerhub/finance-pulse-backend:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    environment:
      # Point at the mongo container on the same network:
      MONGODB_URI: mongodb://mongo:27017/business_management_system
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourdockerhub/finance-pulse-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:80"

  proxy:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/finance-pulse.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo_data:
