services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    image: isarath4/finance-pulse-backend:latest
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    environment:
      MONGODB_URI: mongodb://mongo:27017/business_management_system
    depends_on:
      - mongo
    # expose only to the Docker network for Nginx to reach
    expose:
      - "5000"

  frontend:
    image: isarath4/finance-pulse-frontend:latest
    restart: unless-stopped
    # no host ports—Nginx will proxy to this
    expose:
      - "80"

  proxy:
    image: nginx:stable-alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - ./nginx/finance-pulse.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/letsencrypt/live/yourdomain.com/fullchain.pem:ro
      - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/letsencrypt/live/yourdomain.com/privkey.pem:ro

volumes:
  mongo_data:
