name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/finance-pulse-backend:latest \
            -f backend/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USER }}/finance-pulse-backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/finance-pulse-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USER }}/finance-pulse-frontend:latest

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ec2-65-2-127-222.ap-south-1.compute.amazonaws.com
          username: deploy
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure we’re in the deploy user’s home
            cd $HOME

            # Clone the repo if it doesn't exist
            if [ ! -d app ]; then
              git clone https://github.com/Quarksense-Technologies/finance-pulse-crm.git app
            fi

            # Always enter the app directory
            cd app

            # Pull latest changes
            git fetch origin main
            git reset --hard origin/main

            # Build and deploy with Docker Compose
            docker compose -f docker-compose.prod.yml up -d --build
